src/main/java/acme/entities/projects/Project.java
Issue: #71 
Ref of review issue: #141
=> #71/Task-S01-002

src/main/java/acme/forms/DeveloperDashboard.java
=> #48/Task-S03-004 (DeveloperDashboard)

src/main/webapp/WEB-INF/resources/sample-data/developer.csv, src/main/webapp/WEB-INF/resources/sample-data/user-account.csv
=> #49/Task-S03-005 (Developers credentiaals)

src/main/java/acme/roles/Developer.java
=> #50/Task-S03-013 (Developer)

src/main/java/acme/roles/Manager.java
Issue: #75  
Ref of review issue: #155
=> #75/Task-S01-013

src/main/java/acme/entities/objective/Objective.java, src/main/java/acme/entities/objective/ObjectivePriority.java
Issue: #57 
Ref of review issue: #153
=> #57/Task-G-004

src/main/java/acme/forms/ManagerDashBoard.java
Issue: #73 
Ref of review issue: #151
=> #73/Task-S01-004

reports/Student #4/student4.uxf
Pendiente de revisar en el Follow-Up 21/02
=> S04 UML domain model

src/main/java/acme/entities/training/DifficultyLevel.java, src/main/java/acme/entities/training/TrainingModule.java
=> #46/Task-S03-002 (TrainingModule)

src/main/java/acme/roles/Client.java, src/main/webapp/WEB-INF/resources/sample-data/client.csv, src/main/webapp/WEB-INF/resources/sample-data/user-account.csv
=> #86/Task-S02-005 Client Credentials

src/main/java/acme/entities/codeAudits/AuditRecord.java, src/main/java/acme/entities/codeAudits/CodeAudit.java, src/main/java/acme/forms/AuditorDashboard.java, src/main/webapp/WEB-INF/resources/sample-data/auditor.csv, src/main/webapp/WEB-INF/resources/sample-data/user-account.csv, src/main/webapp/WEB-INF/views/messages-en.i18n, src/main/webapp/WEB-INF/views/messages-es.i18n
=> #188/follow up fixes juamarcan8

src/main/java/acme/forms/AdministratorDashboard.java
Issue: #63 
Ref. of review issue: #197
=> #63/Task-G-022

src/main/java/acme/entities/banner/Banner.java
=> #204/Task G-007/R1

src/main/java/acme/roles/Sponsor.java
=> #203/Task S04-013/R1

reports/Group/D02-G-UML.uxf
Issue: #66 
Ref. of review issue: #211
=> #66/Task-G-025

src/main/java/acme/components/BannerAdvisor.java, src/main/java/acme/components/BannerRepository.java, src/main/webapp/WEB-INF/resources/sample-data/banner.csv, src/main/webapp/WEB-INF/views/fragments/footer.jsp
=> #287/Task-G-010: Show banner

src/main/java/acme/features/manager/dashboard/ManagerDashboardController.java, src/main/java/acme/features/manager/dashboard/ManagerDashboardRepository.java, src/main/java/acme/features/manager/dashboard/ManagerDashboardShowService.java, src/main/java/acme/forms/ManagerDashboard.java, src/main/webapp/WEB-INF/views/fragments/menu-en.i18n, src/main/webapp/WEB-INF/views/fragments/menu-es.i18n, src/main/webapp/WEB-INF/views/fragments/menu.jsp, src/main/webapp/WEB-INF/views/manager/manager-dashboard/form.jsp, src/main/webapp/WEB-INF/views/manager/manager-dashboard/messages-en.i18n, src/main/webapp/WEB-INF/views/manager/manager-dashboard/messages-es.i18n
Issue: #269 
Ref of review issue: #330
=> #269/Task-S01-008: Manager dashboard

.gitignore, src/main/java/acme/features/administrator/banner/AdministratorBannerController.java, src/main/java/acme/features/administrator/banner/AdministratorBannerCreateService.java, src/main/java/acme/features/administrator/banner/AdministratorBannerDeleteService.java, src/main/java/acme/features/administrator/banner/AdministratorBannerListService.java, src/main/java/acme/features/administrator/banner/AdministratorBannerRepository.java, src/main/java/acme/features/administrator/banner/AdministratorBannerShowService.java, src/main/java/acme/features/administrator/banner/AdministratorBannerUpdateService.java, src/main/webapp/WEB-INF/views/administrator/banner/form.jsp, src/main/webapp/WEB-INF/views/administrator/banner/list.jsp, src/main/webapp/WEB-INF/views/administrator/banner/messages-en.i18n, src/main/webapp/WEB-INF/views/administrator/banner/messages-es.i18n, src/main/webapp/WEB-INF/views/fragments/menu-en.i18n, src/main/webapp/WEB-INF/views/fragments/menu-es.i18n, src/main/webapp/WEB-INF/views/fragments/menu.jsp
=> #288/Task-G-011: Admin banner features

src/main/java/acme/features/manager/project/ManagerProjectCreateService.java, src/main/java/acme/features/manager/project/ManagerProjectPublishService.java, src/main/java/acme/features/manager/project/ManagerProjectShowService.java, src/main/java/acme/features/manager/project/ManagerProjectUpdateService.java, src/main/java/acme/features/manager/userStory/ManagerUserStoryCreateService.java, src/main/java/acme/features/manager/userStory/ManagerUserStoryPublishService.java, src/main/java/acme/features/manager/userStory/ManagerUserStoryShowService.java, src/main/java/acme/features/manager/userStory/ManagerUserStoryUpdateService.java, src/main/webapp/WEB-INF/views/manager/project/form.jsp, src/main/webapp/WEB-INF/views/manager/user-story/form.jsp
=> #341/Task-S01-Fix: draft mode internationalization in projects and user stories

src/main/java/acme/features/any/project/AnyProjectController.java, src/main/java/acme/features/any/project/AnyProjectListService.java, src/main/java/acme/features/any/project/AnyProjectRepository.java, src/main/java/acme/features/any/project/AnyProjectShowService.java, src/main/webapp/WEB-INF/views/any/project/form.jsp, src/main/webapp/WEB-INF/views/any/project/list.jsp, src/main/webapp/WEB-INF/views/any/project/messages-en.i18n, src/main/webapp/WEB-INF/views/any/project/messages-es.i18n, src/main/webapp/WEB-INF/views/fragments/menu-en.i18n, src/main/webapp/WEB-INF/views/fragments/menu-es.i18n, src/main/webapp/WEB-INF/views/fragments/menu.jsp, src/main/webapp/WEB-INF/views/manager/project/messages-es.i18n
=> #272/Task-S01-019: Anonymous projects listing
